### ISSUE TITLE
Klasse KonsoleAusnahmebehandlung schreiben

### ISSUE THREAD

**Issue by thkwalter** [thkwalter/lorentz-transformation#17]
## Umfang
* Alle ungefangenen Meldungen werden protokolliert
* Auf der Konsole wird eine Fehlermeldung ausgegeben
* Das Programm wird mit einem spezifischen Fehlercode beendet.

## Teilaufgaben
* [x] Methode `fehlermeldungAusgeben()` schreiben #18
* [x] Methode `fehlermeldungProtokollieren()` schreiben #19
* [x] Fehlerbehandlung für die Methode `uncaughtException` schreiben #20
* [x] Konstruktor schreiben #21
