### ISSUE TITLE
Konsolenprogramm initialisieren

### ISSUE THREAD

**Issue by thkwalter** [thkwalter/lorentz-transformation#9]
## Umfang
* Protokollierung initialisieren
* Ausnahmebehandlung initialisieren

## Aufgaben 
* [x] Klasse `SystemException` schreiben
* [x] Klasse `KonfigurationProtokollierung` schreiben
* [x] Aufzählungstyp `ExitCodes` schreiben
* [x] Klasse `KonsoleAusnahmebehandlung` schreiben #17
* [x] Klasse `InitialisierungKonsolenprogramm`verschieben #16 
* [x] Klasse `InitialisierungKonsolenprogramm` schreiben #6 
* [x] Methode `ausnahmebehandlungInitialisieren()` schreiben #15
* [x] Klasse `InitialisierungKonsolenprogramm` überprüfen #22
* [x] Klasse `KonfigurationProtokollierung` überarbeiten
* [x] Klasse `KonsoleFehlerbehandlung` überarbeiten
* [x] Klasse `SystemExitException` überarbeiten #25
* [x] Aufzählungstyp `ExitCodes` überarbeiten #26
